sudo: required 
language: c
compiler:
  - gcc
  - clang
arch: 
  repos: 
    - archlinuxcn=https://repo.archlinuxcn.org/$arch
  packages: 
    - yay 
    - aarch64-linux-gcc
    - grub
    - dracut
    - git
    - acpica
    - python
    - rsync
    - bc
    - xmlto
    - docbook-xsl
    - kmod
    - inetutils
  script: 
    - makepkg -CA
script: 
  - "travis_wait 30 sleep 1800 &"
  - "curl https://raw.githubusercontent.com/fossasia/arch-travis/master/arch-travis.sh -o arch-travis.sh"
  - "bash arch-travis.sh"
deploy: 
  provider: release
  api_key: ${GIT_OAUTH_KEY}
  file: *.tar.*
  skip_cleanup: true
