sudo: required 
language: c
compiler:
  - gcc
  - clang
arch: 
  - arm64
arch_chroot: 
  repos: 
    - archlinuxcn=https://repo.archlinuxcn.org/$arch
  packages: 
    - yay 
    - aarch64-linux-gcc
    - grub
    - dracut
    - acpica
    - python
    - rsync
    - bc
    - xmlto
    - docbook-xsl
    - kmod
    - inetutils
  script: 
    - makepkg -CA
script: 
  - "travis_wait 30 sleep 1800 &"
  - "curl https://raw.githubusercontent.com/fossasia/arch-travis/master/arch-travis.sh -o arch-travis.sh"
  - "sed -i 's/x86_64/aarch64/' arch-travis.sh"
  - "sed -i "s/travis_yml arch script/travis_yml arch_chroot script/" arch-travis.sh"
  - "sed -i "s/travis_yml arch packages/travis_yml arch_chroot packages/" arch-travis.sh"
  - "sed -i "s/travis_yml arch repos/travis_yml arch_chroot repos/" arch-travis.sh"
  - "bash arch-travis.sh"
deploy: 
  provider: releases
  api_key: ${GIT_OAUTH_KEY}
  file_glob: true
  file: *.tar.*
  skip_cleanup: true
