os: linux
language: generic
arch: arm64
dist: focal
services: 
  - docker
install: 
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io -y
before_script:
  - sudo docker build --tag zhanghua00/archlinuxarm-arm64v8-travis:latest .
script: 
  - sudo docker run --rm -v ${PWD}:/home/travis/build_files -u travis -w /home/travis/build_files zhanghua00/archlinuxarm-arm64v8-travis:latest makepkg -dC
deploy: 
  provider: releases
  token: ${GITHUB_TOKEN}
  file: raspberrypi4-uefi-*.tar.zst
  on:
    branch: main
    tags: true
  cleanup: false
  edge: true
  release_notes: CI build packages for PKGBUILD
  name: RaspberryPi UEFI Boot Files
