os: linux
language: generic
arch: arm64
dist: focal
service: 
  - docker
script: 
  - travis_wait docker build -t archlinuxarm-travis:v1 . 
  - docker run -itd --name archlinuxarm-travis -v ${PWD}:/home/travis archlinuxarm-travis:v1
  - travis_wait docker exec -i archlinuxarm-travis su -l travis -c 'makepkg -d'
  - docker stop archlinuarm-travis
deploy: 
  provider: releases
  token: ${GITHUB_TOKEN}
  file: releases/*
after_success:
 - mkdir -p releases 
 - cp *.tar.* releases/

