os: linux
language: generic
arch: arm64
install: 
  - sudo apt-get install libarchive-dev bsdtar python3 python3-pip ninja-build -y
  - git clone git://projects.archlinux.org/pacman.git
  - cd pacman
  - sudo pip3 install meson
  - meson build
  - cd build
  - ninja
  - sudo ninja install
script: 
  - makepkg
deploy: 
  provider: releases
  token: ${GITHUB_TOKEN}
  file: releases/**
after_success:
 - mkdir -p releases 
 - mv *.tar.* releases
env: 
  global:
    - CARCH: aarch64