os: linux
language: shell
arch: arm64
dist: focal
services: 
  - docker
before_install:
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
script: 
  - travis_wait 10 sudo docker build -t archlinuxarm-travis:v1 .
  - travis_wait 30 sudo docker run -i --rm --name archlinuxarm-travis -v ${PWD}:/home/travis/build_files -u travis -w /home/travis/build_files archlinuxarm-travis:v1 makepkg -dC
  - sudo docker stop archlinuxarm-travis
deploy: 
  provider: releases
  token: ${GITHUB_TOKEN}
  file: raspberrypi-uefi-*.tar.zst
  on:
    branch: main
    tags: true
  cleanup: false
  edge: true
  release_notes: CI build packages for PKGBUILD
  name: RaspberryPi UEFI Boot Files
