os: linux
language: generic
arch: arm64
dist: focal
service: 
  - docker
script: 
  - docker build . 
deploy: 
  provider: releases
  token: ${GITHUB_TOKEN}
  file: releases/**
after_success:
 - mkdir -p releases 
 - docker cp agners/archlinuxarm-arm64v8:/home/travis/*.tar.* releases

