os: linux
language: generic
arch: arm64
dist: focal
install: 
  - sudo apt-get install libarchive-dev libarchive-tools ninja-build meson fakeroot iasl -y
  - git clone git://projects.archlinux.org/pacman.git
  - cd pacman
  - meson build
  - cd build
  - ninja
  - travis_wait sudo ninja install
script: 
  - cd ../..
  - makepkg -d
deploy: 
  provider: releases
  token: ${GITHUB_TOKEN}
  file: releases/**
after_success:
 - mkdir -p releases 
 - mv *.tar.* releases
env: 
  global:
    - CARCH: aarch64
