#!/usr/bin/env bash 

echo "Copying /boot/Image to /boot/vmlinux-linux..."
cp /boot/Image /boot/vmlinux-linux
echo "Copying /boot/Image.gz to /boot/vmlinuz-linux..."
cp /boot/Image.gz /boot/vmlinuz-linux
echo "Copying device tree from kernel..."
cp /boot/dtbs/broadcom/bcm2711-rpi-4-b.dtb /boot/bcm2711-rpi-4-b.dtb
