#!/usr/bin/env sh

if [[ -f /boot/cmdline.txt.pacsave ]]
then
	CMDLINE=$(sed 's/^root=.\+ rw //' /boot/cmdline.txt.pacsave)
	echo Use saved parameters inside /boot/cmdline.txt.pacsave 
elif [[ -f /boot/cmdline.txt ]]
then
	CMDLINE=$(sed 's/^root=.\+ rw //' /boot/cmdline.txt)
	echo /boot/cmdline.txt found, that should NOT happen, check it to make sure no ttyAMA0-related parameters inside or your bluetooth may not work.
else
	CMDLINE=rootwait selinux=0 plymouth.enable=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 usbhid.mousepoll=8 snd-bcm2835.enable_compat_alsa=0 audit=0
	echo No cmdline files found, use default cmdline
fi
sed -i "s/^GRUB_CMDLINE_LINUX=\"\"$/GRUB_CMDLINE_LINUX=\"${CMDLINE}\"/" /etc/default/grub
echo "Finished modifying grub cmdline"
