#!/usr/bin/env bash

echo "Creating initramfs image for %KERNVER%..."
if [[ -f /usr/bin/dracut ]]
then
	/usr/bin/dracut /boot/initramfs-%KERNVER%.img %KERNVER% -f
	/usr/bin/dracut /boot/initramfs-%KERNVER%-fallback.img %KERNVER% -f
elif [[ -f /usr/bin/mkinitcpio ]]
then
	/usr/bin/mkinitcpio -p %KERNVER%
fi
if [[ -f /usr/bin/grub-mkconfig ]]
then
	echo "Updating GRUB config..."
	/usr/bin/grub-mkconfig -o /boot/grub/grub.cfg
fi
