#!/usr/bin/env bash

echo "Creating initramfs image for %KERNVER%..."
if [[ -f /usr/bin/dracut ]]
then
	/usr/bin/dracut --hostonly /boot/initramfs-%KERNVER%.img %KERNVER% -f
	/usr/bin/dracut --no-hostonly /boot/initramfs-%KERNVER%-fallback.img %KERNVER% -f
elif [[ -f /usr/bin/mkinitcpio ]]
then
	/usr/bin/mkinitcpio -p %KERNVER%
else
	echo 'No suppported initramfs generator installed.'
fi
