#!/usr/bin/env sh
if [[ -f /boot/cmdline.txt.pacsave ]]
then
	CMDFILE=/boot/cmdline.txt.pacsave
else
	CMDFILE=/boot/cmdline.txt
fi
CMDLINE="$(sed 's/^root=.\+ rw //' ${CMDFILE})"
if [[ ${CMDLINE} != "" ]]
then
	sed -i "s/^GRUB_CMDLINE_LINUX=\"\"$/GRUB_CMDLINE_LINUX=\"${CMDLINE}\"/" /etc/default/grub
	echo "Finished modifying grub cmdline"
else
	echo "No need to modify grub cmdline because \${CMDFILE} is empty"
fi 
