name: Auto Build Arch Packages
on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'pacman-hooks'
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches: 
      - main
    paths-ignore:
      - 'pacman-hooks'
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'

  workflow_dispatch:

jobs:
  package-build:
    name: Build and Upload Packages for PKGBUILD in this repository
    runs-on: ubuntu-24.04-arm
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: bash start-build.sh
      
      - name: Generare Release info
        if: ${{ github.event_name == 'push' }}
        id: release-info
        run: |
          cd out
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "sums<<$EOF" >> "$GITHUB_OUTPUT"
          sha256sum *.pkg.tar.* >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
          echo date=$(date -I | sed s/-//g) >> "$GITHUB_OUTPUT"
          
      
      - name: Push to GitHub Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with: 
          draft: false
          generate_release_notes: true
          prerelease: false
          tag_name: ${{ steps.release-info.outputs.date }}
          files: "out/*.pkg.tar.*"
          name: Raspberry Pi 4 UEFI Boot Packages for Arch Based Linux Distribution
          body: |
            CI Build for commit ${{ github.sha }}
            
            sha256sums:
            ```
            ${{ steps.release-info.outputs.sums }}
            ```
