name: Build Docker Image and Push to Docker Hub
on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .dockerignore
      - start-build.sh
  pull_request:
    branches: [ main ]
    paths:
      - Dockerfile
      - .dockerignore
      - start-build.sh
jobs:
  build:
    name: Build Docker Image for Building Arch Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/archlinux-ci:latest
          push: true
