name: Auto Build Arch Packages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits),'skip_ci') == false 
    # Use skip_ci in commit info to skip Auto Build
    name: Build and Upload Packages for PKGBUILD in this repository
    runs-on: ubuntu-latest
    steps:
      - name: Install Requirement
        run: sudo apt-get install qemu-user-static -y
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/archlinuxarm-ci-arm64:latest
          push: true
      - name: Run QEMU User Static Docker Image to Build
        run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build Package use Images Built before 
        uses: addnab/docker-run-action@v1
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/archlinuxarm-ci-arm64:latest
          options: -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v ${{ github.workspace }}:/home/builder/build_files -w /home/builder/build_files -u builder --rm
          run: |
            sudo chown -R builder:builder /home/builder/build_files 
            makepkg -dC
          shell: bash
      - name: Push to GitHub Releases
        uses: ncipollo/release-action@v1
        with: 
          artifacts: raspberrypi4-uefi-*.pkg.tar.zst
          name: Raspberry Pi 4 UEFI Boot Packages for Arch Based Linux Distribution
          body: CI Build for commit ${{ github.sha }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
  
