name: Auto Build Arch Packages
on:
  push:
    branches: [ main ]
    paths:
      - 'PKGBUILD'
      - '**.patch'
      - 'dracut-update-initramfs'
      - '**.hook'
      - '.github/workflow/build-packages.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'PKGBUILD'
      - '**.patch'
      - 'dracut-update-initramfs'
      - '**.hook'
      - '.github/workflow/build-packages.yml'
  workflow_dispatch:
  schedule: 
    - cron: '33 3 3,10,17,24,31 * *'
jobs:
  build:
    name: Build and Upload Packages for PKGBUILD in this repository
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        generic: [1,0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show event name
        run: echo ${{ github.event_name }}
      - name: Disable Mirror
        run: sed -i '13,19s/^/#/' PKGBUILD
      - name: Build Package use Image Built before
        run: sudo docker run --rm --privileged=true --env CI=true --env USE_GENERIC_KERNEL=${{ matrix.generic }} -v ${{ github.workspace }}:/home/builder/build_files ${{ secrets.DOCKERHUB_USERNAME }}/archlinux-ci:latest
      - name: Generare Release info
        run: |
          echo TAG=$(cat PKGBUILD | sed "/pkgver=.\+/p" -n | sed "s/pkgver=//") >> $GITHUB_ENV
          echo PKGREL=$(cat PKGBUILD | sed "/pkgrel=.\+/p" -n | sed "s/pkgrel=//") >> $GITHUB_ENV
          echo 'SUMS<<EOF' >> $GITHUB_ENV
          sha256sum *.pkg.tar.zst >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8) >> $GITHUB_ENV
      - name: Push to GitHub Releases
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with: 
          draft: false
          prerelease: false
          tag_name: ${{ env.TAG }}-CI-${{ env.SHORT_SHA }}-${{ matrix.generic }}
          files: |
            raspberrypi4-uefi-firmware-git-${{ env.TAG }}-${{ env.PKGREL }}-aarch64.pkg.tar.zst
            raspberrypi4-uefi-kernel-git-${{ env.TAG }}-${{ env.PKGREL }}-aarch64.pkg.tar.zst
            raspberrypi4-uefi-kernel-headers-git-${{ env.TAG }}-${{ env.PKGREL }}-aarch64.pkg.tar.zst
            raspberrypi4-uefi-kernel-api-headers-git-${{ env.TAG }}-${{ env.PKGREL }}-aarch64.pkg.tar.zst
          name: Raspberry Pi 4 UEFI Boot Packages for Arch Based Linux Distribution
          body: |
            CI Build for commit ${{ github.sha }}
            
            sha256sums:
            ```
            ${{ env.SUMS }}
            ```

            Tag ends with 0 means raspberrypi kernel, 1 means generic kernel.
            
      - name: Recover Mirror before commit
        if: ${{ github.event_name == 'schedule' }} 
        run: |
          sudo chown -R runner:docker .
          sed -i '13,19s/^#//' PKGBUILD
      - name: Commit if version string changed when running CI at schedule
        if: ${{ github.event_name == 'schedule' }}
        uses: stefanzweifel/git-auto-commit-action@v4
