name: Auto Build Arch Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1 
      - uses: actions/checkout@v2 
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag archlinuxarm-ci:v1
      - name: Build Package
        run: docker run -v ${GITHUB_WORKSPACE}:/home/travis/build_files -u travis -w /home/travis/build_files archlinuxarm-ci:v1 makepkg -Cd
