name: Build Docker Image and Push to Docker Hub
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/archlinuxarm-ci-arm64:latest
          push: true
