name: Auto Build Arch Packages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build and Upload Packages for PKGBUILD in this repository
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1 
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/archlinuxarm-ci-arm64:latest
          push: true
      - name: Build Package use Images Built before 
        uses: addnab/docker-run-action@v1
        with:
          shell: bash
          run: makepkg -Cd
          options: -v ${GITHUB_WORKSPACE}:/home/builder/build_files -u builder -w /home/builder/build_files

#      - name: Push to GitHub Releases
#        uses: actions/create-release@v1
#        env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with: 
#           tag_name: ${{ github.ref }}
  
